In [3]:
import zipfile

# Path to the zip file
zip_file_path = '/content/movie.zip'
# Directory where to extract
extract_to_dir = 'Movie/'

# Open the zip file
with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    # Extract all contents to the specified directory
    zip_ref.extractall(extract_to_dir)

print(f"Files extracted to {extract_to_dir}")

Files extracted to Movie/

In [4]:
import nltk
nltk.download('punkt_tab')
from nltk.tokenize import word_tokenize,sent_tokenize
import spacy
from spacy.lang.en import English
from spacy.lang.en.stop_words import STOP_WORDS
nlp=spacy.load("en_core_web_sm")
import pandas as pd
data=pd.read_csv("/content/Movie/movie_review.csv")
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer,WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [5]:
data.head()

,fold_id,cv_tag,html_id,sent_id,text,tag
0,0,cv000,29590,0,films adapted from comic books have had plenty...,pos
1,0,cv000,29590,1,"for starters , it was created by alan moore ( ...",pos
2,0,cv000,29590,2,to say moore and campbell thoroughly researche...,pos
3,0,cv000,29590,3,"the book ( or "" graphic novel , "" if you will ...",pos
4,0,cv000,29590,4,"in other words , don't dismiss this film becau...",pos

In [6]:
data['tag'].value_counts()

tag
pos    32937
neg    31783
Name: count, dtype: int64

In [7]:
data['review']=data['tag'].apply(lambda x: 1 if x=='neg' else 0)
data.head()

,fold_id,cv_tag,html_id,sent_id,text,tag,review
0,0,cv000,29590,0,films adapted from comic books have had plenty...,pos,0
1,0,cv000,29590,1,"for starters , it was created by alan moore ( ...",pos,0
2,0,cv000,29590,2,to say moore and campbell thoroughly researche...,pos,0
3,0,cv000,29590,3,"the book ( or "" graphic novel , "" if you will ...",pos,0
4,0,cv000,29590,4,"in other words , don't dismiss this film becau...",pos,0

In [8]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
ps=PorterStemmer()
lemmatizer=WordNetLemmatizer()
stopwords=set(stopwords.words('english'))

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

In [9]:
data['tokens']=data['text'].apply( word_tokenize)
data.head()

,fold_id,cv_tag,html_id,sent_id,text,tag,review,tokens
0,0,cv000,29590,0,films adapted from comic books have had plenty...,pos,0,"[films, adapted, from, comic, books, have, had..."
1,0,cv000,29590,1,"for starters , it was created by alan moore ( ...",pos,0,"[for, starters, ,, it, was, created, by, alan,..."
2,0,cv000,29590,2,to say moore and campbell thoroughly researche...,pos,0,"[to, say, moore, and, campbell, thoroughly, re..."
3,0,cv000,29590,3,"the book ( or "" graphic novel , "" if you will ...",pos,0,"[the, book, (, or, ``, graphic, novel, ,, ``, ..."
4,0,cv000,29590,4,"in other words , don't dismiss this film becau...",pos,0,"[in, other, words, ,, do, n't, dismiss, this, ..."

In [10]:
data['stopwords']=data['tokens'].apply(lambda x:[word.lower()for word in x if word.lower() not in stopwords and word.isalpha()])
data.head()

,fold_id,cv_tag,html_id,sent_id,text,tag,review,tokens,stopwords
0,0,cv000,29590,0,films adapted from comic books have had plenty...,pos,0,"[films, adapted, from, comic, books, have, had...","[films, adapted, comic, books, plenty, success..."
1,0,cv000,29590,1,"for starters , it was created by alan moore ( ...",pos,0,"[for, starters, ,, it, was, created, by, alan,...","[starters, created, alan, moore, eddie, campbe..."
2,0,cv000,29590,2,to say moore and campbell thoroughly researche...,pos,0,"[to, say, moore, and, campbell, thoroughly, re...","[say, moore, campbell, thoroughly, researched,..."
3,0,cv000,29590,3,"the book ( or "" graphic novel , "" if you will ...",pos,0,"[the, book, (, or, ``, graphic, novel, ,, ``, ...","[book, graphic, novel, pages, long, includes, ..."
4,0,cv000,29590,4,"in other words , don't dismiss this film becau...",pos,0,"[in, other, words, ,, do, n't, dismiss, this, ...","[words, dismiss, film, source]"

In [11]:
data['tokens'].iloc[1]

['for',
 'starters',
 ',',
 'it',
 'was',
 'created',
 'by',
 'alan',
 'moore',
 '(',
 'and',
 'eddie',
 'campbell',
 ')',
 ',',
 'who',
 'brought',
 'the',
 'medium',
 'to',
 'a',
 'whole',
 'new',
 'level',
 'in',
 'the',
 'mid',
 "'80s",
 'with',
 'a',
 '12-part',
 'series',
 'called',
 'the',
 'watchmen',
 '.']

In [12]:
len(data['tokens'].iloc[1])

36

In [13]:
data['stopwords'].iloc[1]

['starters',
 'created',
 'alan',
 'moore',
 'eddie',
 'campbell',
 'brought',
 'medium',
 'whole',
 'new',
 'level',
 'mid',
 'series',
 'called',
 'watchmen']

In [14]:
len(data['stopwords'].iloc[1])

15

In [15]:
data['stemmimg']=data['stopwords'].apply(lambda x:[ps.stem(word) for word in x])
data.head()

,fold_id,cv_tag,html_id,sent_id,text,tag,review,tokens,stopwords,stemmimg
0,0,cv000,29590,0,films adapted from comic books have had plenty...,pos,0,"[films, adapted, from, comic, books, have, had...","[films, adapted, comic, books, plenty, success...","[film, adapt, comic, book, plenti, success, wh..."
1,0,cv000,29590,1,"for starters , it was created by alan moore ( ...",pos,0,"[for, starters, ,, it, was, created, by, alan,...","[starters, created, alan, moore, eddie, campbe...","[starter, creat, alan, moor, eddi, campbel, br..."
2,0,cv000,29590,2,to say moore and campbell thoroughly researche...,pos,0,"[to, say, moore, and, campbell, thoroughly, re...","[say, moore, campbell, thoroughly, researched,...","[say, moor, campbel, thoroughli, research, sub..."
3,0,cv000,29590,3,"the book ( or "" graphic novel , "" if you will ...",pos,0,"[the, book, (, or, ``, graphic, novel, ,, ``, ...","[book, graphic, novel, pages, long, includes, ...","[book, graphic, novel, page, long, includ, nea..."
4,0,cv000,29590,4,"in other words , don't dismiss this film becau...",pos,0,"[in, other, words, ,, do, n't, dismiss, this, ...","[words, dismiss, film, source]","[word, dismiss, film, sourc]"

In [16]:
data['lemma']=data['stopwords'].apply(lambda x:[lemmatizer.lemmatize(word) for word in x])
data['stemmimg'].iloc[2]

['say',
 'moor',
 'campbel',
 'thoroughli',
 'research',
 'subject',
 'jack',
 'ripper',
 'would',
 'like',
 'say',
 'michael',
 'jackson',
 'start',
 'look',
 'littl',
 'odd']

In [17]:
data['lemma'].iloc[2]

['say',
 'moore',
 'campbell',
 'thoroughly',
 'researched',
 'subject',
 'jack',
 'ripper',
 'would',
 'like',
 'saying',
 'michael',
 'jackson',
 'starting',
 'look',
 'little',
 'odd']

In [18]:
data.head()

,fold_id,cv_tag,html_id,sent_id,text,tag,review,tokens,stopwords,stemmimg,lemma
0,0,cv000,29590,0,films adapted from comic books have had plenty...,pos,0,"[films, adapted, from, comic, books, have, had...","[films, adapted, comic, books, plenty, success...","[film, adapt, comic, book, plenti, success, wh...","[film, adapted, comic, book, plenty, success, ..."
1,0,cv000,29590,1,"for starters , it was created by alan moore ( ...",pos,0,"[for, starters, ,, it, was, created, by, alan,...","[starters, created, alan, moore, eddie, campbe...","[starter, creat, alan, moor, eddi, campbel, br...","[starter, created, alan, moore, eddie, campbel..."
2,0,cv000,29590,2,to say moore and campbell thoroughly researche...,pos,0,"[to, say, moore, and, campbell, thoroughly, re...","[say, moore, campbell, thoroughly, researched,...","[say, moor, campbel, thoroughli, research, sub...","[say, moore, campbell, thoroughly, researched,..."
3,0,cv000,29590,3,"the book ( or "" graphic novel , "" if you will ...",pos,0,"[the, book, (, or, ``, graphic, novel, ,, ``, ...","[book, graphic, novel, pages, long, includes, ...","[book, graphic, novel, page, long, includ, nea...","[book, graphic, novel, page, long, includes, n..."
4,0,cv000,29590,4,"in other words , don't dismiss this film becau...",pos,0,"[in, other, words, ,, do, n't, dismiss, this, ...","[words, dismiss, film, source]","[word, dismiss, film, sourc]","[word, dismiss, film, source]"

In [19]:
data['processed_text']=data['lemma'].apply(lambda x:" ".join(x)) # Corrected to join the actual stemming (x)

In [20]:
vectorizer=CountVectorizer()
x=vectorizer.fit_transform(data['processed_text'])
data.head()

,fold_id,cv_tag,html_id,sent_id,text,tag,review,tokens,stopwords,stemmimg,lemma,processed_text
0,0,cv000,29590,0,films adapted from comic books have had plenty...,pos,0,"[films, adapted, from, comic, books, have, had...","[films, adapted, comic, books, plenty, success...","[film, adapt, comic, book, plenti, success, wh...","[film, adapted, comic, book, plenty, success, ...",film adapted comic book plenty success whether...
1,0,cv000,29590,1,"for starters , it was created by alan moore ( ...",pos,0,"[for, starters, ,, it, was, created, by, alan,...","[starters, created, alan, moore, eddie, campbe...","[starter, creat, alan, moor, eddi, campbel, br...","[starter, created, alan, moore, eddie, campbel...",starter created alan moore eddie campbell brou...
2,0,cv000,29590,2,to say moore and campbell thoroughly researche...,pos,0,"[to, say, moore, and, campbell, thoroughly, re...","[say, moore, campbell, thoroughly, researched,...","[say, moor, campbel, thoroughli, research, sub...","[say, moore, campbell, thoroughly, researched,...",say moore campbell thoroughly researched subje...
3,0,cv000,29590,3,"the book ( or "" graphic novel , "" if you will ...",pos,0,"[the, book, (, or, ``, graphic, novel, ,, ``, ...","[book, graphic, novel, pages, long, includes, ...","[book, graphic, novel, page, long, includ, nea...","[book, graphic, novel, page, long, includes, n...",book graphic novel page long includes nearly c...
4,0,cv000,29590,4,"in other words , don't dismiss this film becau...",pos,0,"[in, other, words, ,, do, n't, dismiss, this, ...","[words, dismiss, film, source]","[word, dismiss, film, sourc]","[word, dismiss, film, source]",word dismiss film source

In [21]:
words=vectorizer.get_feature_names_out()
bow=pd.DataFrame(x.toarray(),columns=words)
print(bow.head())

   aa  aaa  aaaaaaaaah  aaaaaaaahhhh  aaaaaah  aaaahhhs  aahs  aaliyah  \
0   0    0           0             0        0         0     0        0
1   0    0           0             0        0         0     0        0
2   0    0           0             0        0         0     0        0
3   0    0           0             0        0         0     0        0
4   0    0           0             0        0         0     0        0

   aalyah  aamir  ...  zuehlke  zuko  zukovsky  zulu  zundel  zurg  zweibel  \
0       0      0  ...        0     0         0     0       0     0        0
1       0      0  ...        0     0         0     0       0     0        0
2       0      0  ...        0     0         0     0       0     0        0
3       0      0  ...        0     0         0     0       0     0        0
4       0      0  ...        0     0         0     0       0     0        0

   zwick  zwigoff  zycie
0      0        0      0
1      0        0      0
2      0        0      0
3      0        0      0
4      0        0      0

[5 rows x 33632 columns]

In [22]:
a=data[['text','tokens','stopwords','stemmimg','processed_text']]
a

,text,tokens,stopwords,stemmimg,processed_text
0,films adapted from comic books have had plenty...,"[films, adapted, from, comic, books, have, had...","[films, adapted, comic, books, plenty, success...","[film, adapt, comic, book, plenti, success, wh...",film adapted comic book plenty success whether...
1,"for starters , it was created by alan moore ( ...","[for, starters, ,, it, was, created, by, alan,...","[starters, created, alan, moore, eddie, campbe...","[starter, creat, alan, moor, eddi, campbel, br...",starter created alan moore eddie campbell brou...
2,to say moore and campbell thoroughly researche...,"[to, say, moore, and, campbell, thoroughly, re...","[say, moore, campbell, thoroughly, researched,...","[say, moor, campbel, thoroughli, research, sub...",say moore campbell thoroughly researched subje...
3,"the book ( or "" graphic novel , "" if you will ...","[the, book, (, or, ``, graphic, novel, ,, ``, ...","[book, graphic, novel, pages, long, includes, ...","[book, graphic, novel, page, long, includ, nea...",book graphic novel page long includes nearly c...
4,"in other words , don't dismiss this film becau...","[in, other, words, ,, do, n't, dismiss, this, ...","[words, dismiss, film, source]","[word, dismiss, film, sourc]",word dismiss film source
...,...,...,...,...,...
64715,that lack of inspiration can be traced back to...,"[that, lack, of, inspiration, can, be, traced,...","[lack, inspiration, traced, back, insipid, cha...","[lack, inspir, trace, back, insipid, charact]",lack inspiration traced back insipid character
64716,like too many of the skits on the current inca...,"[like, too, many, of, the, skits, on, the, cur...","[like, many, skits, current, incarnation, roxb...","[like, mani, skit, current, incarn, roxburi, g...",like many skit current incarnation roxbury guy...
64717,"after watching one of the "" roxbury "" skits on...","[after, watching, one, of, the, ``, roxbury, `...","[watching, one, roxbury, skits, snl, come, awa...","[watch, one, roxburi, skit, snl, come, away, c...",watching one roxbury skit snl come away charac...
64718,"bump unsuspecting women , and . . . that's all .","[bump, unsuspecting, women, ,, and, ., ., ., t...","[bump, unsuspecting, women]","[bump, unsuspect, women]",bump unsuspecting woman
64719,"after watching _a_night_at_the_roxbury_ , you'...","[after, watching, _a_night_at_the_roxbury_, ,,...","[watching, left, exactly]","[watch, left, exactli]",watching left exactly

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(bow,data['review'],test_size=0.2,random_state=42)
x_train.shape

In [ ]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

In [ ]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_test,y_test)
y_pred=lr.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

In [ ]:
from sklearn.naive_bayes import MultinomialNB
nb=MultinomialNB()
nb.fit(x_train,y_train)
y_pred=nb.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

In [ ]:
from sklearn.naive_bayes import MultinomialNB
nb=MultinomialNB(alpha=10)
nb.fit(x_test,y_test)
y_pred=nb.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))